-- create database katzmoviez; 
use katzmoviez;

-- CREATE TABLE movies (
--   id INT PRIMARY KEY,
--   moviename VARCHAR(255) NOT NULL,
--   directedby VARCHAR(255) NOT NULL,
--   origin VARCHAR(255) NOT NULL,
--   ticketprice INT NOT NULL
-- );

-- INSERT INTO movies (id, moviename, directedby, origin, ticketprice)
-- VALUES
--   (1, 'Avatar', 'James Cameron', 'USA', 15),
--   (2, 'The Shawshank Redemption', 'Frank Darabont', 'USA', 12),
--   (3, 'Inception', 'Christopher Nolan', 'USA', 10),
--   (4, 'The Godfather', 'Francis Ford Coppola', 'USA', 12),
--   (5, 'Pulp Fiction', 'Quentin Tarantino', 'USA', 14),
--   (6, 'The Dark Knight', 'Christopher Nolan', 'USA', 13),
--   (7, 'Forrest Gump', 'Robert Zemeckis', 'USA', 11),
--   (8, 'Fight Club', 'David Fincher', 'USA', 10),
--   (9, 'The Matrix', 'The Wachowskis', 'USA', 12),
--   (10, 'Interstellar', 'Christopher Nolan', 'USA', 14),
--   (11, 'Forrest Gump', 'Robert Zemeckis', 'USA', 11),
--   (12, 'Schindler''s List', 'Steven Spielberg', 'USA', 12),
--   (13, 'The Lord of the Rings: The Fellowship of the Ring', 'Peter Jackson', 'New Zealand', 13),
--   (14, 'The Lion King', 'Roger Allers, Rob Minkoff', 'USA', 11),
--   (15, 'The Avengers', 'Joss Whedon', 'USA', 13),
--   (16, 'The Titanic', 'James Cameron', 'USA', 12),
--   (17, 'Gladiator', 'Ridley Scott', 'USA', 11),
--   (18, 'Finding Nemo', 'Andrew Stanton, Lee Unkrich', 'USA', 10),
--   (19, 'The Dark Knight Rises', 'Christopher Nolan', 'USA', 12),
--   (20, 'The Matrix Reloaded', 'The Wachowskis', 'USA', 14),
--   (21, 'Inception', 'Christopher Nolan', 'USA', 10),
--   (22, 'Forrest Gump', 'Robert Zemeckis', 'USA', 11),
--   (23, 'The Godfather: Part II', 'Francis Ford Coppola', 'USA', 12),
--   (24, 'The Lord of the Rings: The Two Towers', 'Peter Jackson', 'New Zealand', 13),
--   (25, 'Shrek', 'Andrew Adamson, Vicky Jenson', 'USA', 9),
--   (26, 'The Shawshank Redemption', 'Frank Darabont', 'USA', 12),
--   (27, 'The Lion King', 'Roger Allers, Rob Minkoff', 'USA', 11),
--   (28, 'Inception', 'Christopher Nolan', 'USA', 10),
--   (29, 'The Dark Knight', 'Christopher Nolan', 'USA', 13),
--   (30, 'Forrest Gump', 'Robert Zemeckis', 'USA', 11),
--   (31, 'Forrest Gump', 'Robert Zemeckis', 'USA', 11),
--   (32, 'Fight Club', 'David Fincher', 'USA', 10),
--   (33, 'The Matrix', 'The Wachowskis', 'USA', 12),
--   (34, 'Interstellar', 'Christopher Nolan', 'USA', 14),
--   (35, 'Forrest Gump', 'Robert Zemeckis', 'USA', 11),
--   (36, 'The Shawshank Redemption', 'Frank Darabont', 'USA', 12),
--   (37, 'The Lord of the Rings: The Return of the King', 'Peter Jackson', 'New Zealand', 13),
--   (38, 'The Lion King', 'Roger Allers, Rob Minkoff', 'USA', 11),
--   (39, 'The Avengers', 'Joss Whedon', 'USA', 13),
--   (40, 'The Titanic', 'James Cameron', 'USA', 12),
--   (41, 'Gladiator', 'Ridley Scott', 'USA', 11),
--   (42, 'Finding Nemo', 'Andrew Stanton, Lee Unkrich', 'USA', 10),
--   (43, 'The Dark Knight Rises', 'Christopher Nolan', 'USA', 12),
--   (44, 'The Matrix Reloaded', 'The Wachowskis', 'USA', 14),
--   (45, 'Inception', 'Christopher Nolan', 'USA', 10),
--   (46, 'Forrest Gump', 'Robert Zemeckis', 'USA', 11),
--   (47, 'The Godfather: Part II', 'Francis Ford Coppola', 'USA', 12),
--   (48, 'The Lord of the Rings: The Two Towers', 'Peter Jackson', 'New Zealand', 13),
--   (49, 'Shrek', 'Andrew Adamson, Vicky Jenson', 'USA', 9),
--   (50, 'Avatar', 'James Cameron', 'USA', 15);
-- select * from movies;

--  v-02

DROP TABLE category;
CREATE TABLE category (
    id INT primary key,
    name VARCHAR(255) NOT NULL
);

INSERT INTO category (id, name)
VALUES
    (1, 'Hollywood'),
    (2, 'Korean'),
    (3, 'Bollywood'),
    (4, 'Tamil');

DROP TABLE movies;
CREATE TABLE movies (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    director VARCHAR(255),
    origin VARCHAR(255),
    categoryid INT,
    FOREIGN KEY (categoryid) REFERENCES category(id)
);
INSERT INTO movies (name, director, origin, categoryid)
VALUES
    ('The Great Adventure', 'John Director', 'Hollywood', 1);

INSERT INTO movies (name, director, origin, categoryid)
VALUES
    ('Mystic Dreams', 'Jane Director', 'Hollywood', 1),
    ('Sunset Boulevard', 'Michael Director', 'Hollywood', 1),
    ('Midnight Echoes', 'Emily Director', 'Hollywood', 1),
    ('Starship Odyssey', 'Robert Director', 'Hollywood', 1),
    ('Lost in Time', 'Amanda Director', 'Hollywood', 1),
    ('City of Legends', 'David Director', 'Hollywood', 1),
    ('Eternal Sunshine', 'Sophia Director', 'Hollywood', 1),
    ('Whispering Shadows', 'William Director', 'Hollywood', 1),
    ('Silver Screen Dreams', 'Olivia Director', 'Hollywood', 1),
    ('Sapphire Skies', 'Daniel Director', 'Hollywood', 1),
    ('Astral Symphony', 'Isabella Director', 'Hollywood', 1),
    ('Golden Horizons', 'Ethan Director', 'Hollywood', 1),
    ('Echoes of Yesterday', 'Emma Director', 'Hollywood', 1),
    ('Rising Stars', 'Alexander Director', 'Hollywood', 1),
    ('Crimson Chronicles', 'Mia Director', 'Hollywood', 1),
    ('Neon Nights', 'James Director', 'Hollywood', 1),
    ('Moonlit Melodies', 'Ava Director', 'Hollywood', 1),
    ('Serenade in Blue', 'Liam Director', 'Hollywood', 1),
    ('Waves of Destiny', 'Sophia Director', 'Hollywood', 1),
    ('Whispers in the Dark', 'Noah Director', 'Hollywood', 1),
    ('Twilight Rhapsody', 'Olivia Director', 'Hollywood', 1),
    ('Enchanted Dreams', 'Lucas Director', 'Hollywood', 1),
    ('Harmony Call', 'Amelia Director', 'Hollywood', 1),
    ('Azure Enigma', 'Elijah Director', 'Hollywood', 1),
    ('Echoes of Eternity', 'Charlotte Director', 'Hollywood', 1),
    ('Crimson Odyssey', 'Benjamin Director', 'Hollywood', 1),
    ('Silent Echo', 'Chloe Director', 'Hollywood', 1),
    ('Labyrinth of Legends', 'Carter Director', 'Hollywood', 1),
    ('Whispering Winds', 'Grace Director', 'Hollywood', 1),
    ('Emerald Embrace', 'Henry Director', 'Hollywood', 1),
    ('Mystic Serenade', 'Ella Director', 'Hollywood', 1),
    ('Stardust Reverie', 'Jackson Director', 'Hollywood', 1),
    ('Eternal Echoes', 'Scarlett Director', 'Hollywood', 1),
    ('Celestial Waltz', 'Liam Director', 'Hollywood', 1),
    ('Melodies of Time', 'Ava Director', 'Hollywood', 1),
    ('Sapphire Sonata', 'Mason Director', 'Hollywood', 1),
    ('Moonlit Memories', 'Charlotte Director', 'Hollywood', 1),
    ('Golden Dreams', 'Ethan Director', 'Hollywood', 1),
    ('Astral Whispers', 'Olivia Director', 'Hollywood', 1),
    ('Whispering Waters', 'Noah Director', 'Hollywood', 1);

INSERT INTO movies (name, director, origin, categoryid)
VALUES
    ('Love in Seoul', 'Park Director', 'Korea', 2),
    ('Rainy Days', 'Kim Director', 'Korea', 2),
    ('Eternal Promise', 'Lee Director', 'Korea', 2),
    ('City Lights', 'Choi Director', 'Korea', 2),
    ('Winter Sonata', 'Kang Director', 'Korea', 2),
    ('Whispering Breeze', 'Yoon Director', 'Korea', 2),
    ('Falling Petals', 'Jung Director', 'Korea', 2),
    ('Starlit Night', 'Moon Director', 'Korea', 2),
    ('Springtime Melody', 'Park Director', 'Korea', 2),
    ('Misty Mountains', 'Oh Director', 'Korea', 2),
    ('Crimson Sky', 'Song Director', 'Korea', 2),
    ('Solitude', 'Kim Director', 'Korea', 2),
    ('Journey Home', 'Hwang Director', 'Korea', 2),
    ('Love and Laughter', 'Choi Director', 'Korea', 2),
    ('Fading Memories', 'Lee Director', 'Korea', 2),
    ('Radiant Beauty', 'Jin Director', 'Korea', 2),
    ('Dreams of Tomorrow', 'Park Director', 'Korea', 2),
    ('Autumn Leaves', 'Yoo Director', 'Korea', 2),
    ('Floral Delight', 'Kim Director', 'Korea', 2),
    ('Beyond Borders', 'Han Director', 'Korea', 2),
    ('Morning Sunshine', 'Lee Director', 'Korea', 2),
    ('Ocean Serenity', 'Kang Director', 'Korea', 2),
    ('Enchanted Forest', 'Choi Director', 'Korea', 2),
    ('Endless Love', 'Seo Director', 'Korea', 2),
    ('Secret Garden', 'Park Director', 'Korea', 2),
    ('Moonlit Reflections', 'Song Director', 'Korea', 2),
    ('Starry Night', 'Kim Director', 'Korea', 2),
    ('Eternal Flame', 'Jung Director', 'Korea', 2),
    ('Lullaby of the Heart', 'Yoon Director', 'Korea', 2),
    ('Promise of Spring', 'Choi Director', 'Korea', 2),
    ('Whispers of Destiny', 'Lee Director', 'Korea', 2),
    ('Harmony of Souls', 'Hwang Director', 'Korea', 2),
    ('Gentle Rain', 'Park Director', 'Korea', 2),
    ('Cherry Blossom Love', 'Kim Director', 'Korea', 2),
    ('Mystic Moon', 'Jin Director', 'Korea', 2),
    ('Dancing Shadows', 'Choi Director', 'Korea', 2),
    ('Falling Stars', 'Lee Director', 'Korea', 2),
    ('Autumn Serenade', 'Song Director', 'Korea', 2),
    ('Echoes of Love', 'Kim Director', 'Korea', 2),
    ('Beneath the Moon', 'Yoo Director', 'Korea', 2),
    ('Emerald Dreams', 'Kang Director', 'Korea', 2);

INSERT INTO movies (name, director, origin, categoryid)
VALUES
    ('Dilwale Dulhania Le Jayenge', 'Aditya Chopra', 'India', 3),
    ('Sholay', 'Ramesh Sippy', 'India', 3),
    ('3 Idiots', 'Rajkumar Hirani', 'India', 3),
    ('Kabhi Khushi Kabhie Gham', 'Karan Johar', 'India', 3),
    ('Lagaan', 'Ashutosh Gowariker', 'India', 3),
    ('Dil Chahta Hai', 'Farhan Akhtar', 'India', 3),
    ('Kuch Kuch Hota Hai', 'Karan Johar', 'India', 3),
    ('Mughal-e-Azam', 'K. Asif', 'India', 3),
    ('My Name Is Khan', 'Karan Johar', 'India', 3),
    ('Koi Mil Gaya', 'Rakesh Roshan', 'India', 3),
    ('Dangal', 'Nitesh Tiwari', 'India', 3),
    ('PK', 'Rajkumar Hirani', 'India', 3),
    ('Golmaal: Fun Unlimited', 'Rohit Shetty', 'India', 3),
    ('Kabir Singh', 'Sandeep Reddy Vanga', 'India', 3),
    ('Dabangg', 'Abhinav Kashyap', 'India', 3),
    ('Bajrangi Bhaijaan', 'Kabir Khan', 'India', 3),
    ('Chennai Express', 'Rohit Shetty', 'India', 3),
    ('Padmaavat', 'Sanjay Leela Bhansali', 'India', 3),
    ('Andhadhun', 'Sriram Raghavan', 'India', 3),
    ('Uri: The Surgical Strike', 'Aditya Dhar', 'India', 3),
    ('Dil Se..', 'Mani Ratnam', 'India', 3),
    ('Jab We Met', 'Imtiaz Ali', 'India', 3),
    ('Bahubali: The Beginning', 'S. S. Rajamouli', 'India', 3),
    ('Mera Naam Joker', 'Raj Kapoor', 'India', 3),
    ('Gully Boy', 'Zoya Akhtar', 'India', 3),
    ('Kesari', 'Anurag Singh', 'India', 3),
    ('Queen', 'Vikas Bahl', 'India', 3),
    ('Raazi', 'Meghna Gulzar', 'India', 3),
    ('Dil Dhadakne Do', 'Zoya Akhtar', 'India', 3),
    ('Ae Dil Hai Mushkil', 'Karan Johar', 'India', 3),
    ('Rang De Basanti', 'Rakeysh Omprakash Mehra', 'India', 3),
    ('Don', 'Farhan Akhtar', 'India', 3),
    ('Om Shanti Om', 'Farah Khan', 'India', 3),
    ('Taare Zameen Par', 'Aamir Khan', 'India', 3),
    ('Kabhi Alvida Naa Kehna', 'Karan Johar', 'India', 3),
    ('Dhoom', 'Sanjay Gadhvi', 'India', 3),
    ('Munna Bhai M.B.B.S.', 'Rajkumar Hirani', 'India', 3),
    ('Gadar: Ek Prem Katha', 'Anil Sharma', 'India', 3),
    ('Namak Halaal', 'Prakash Mehra', 'India', 3),
    ('Lage Raho Munna Bhai', 'Rajkumar Hirani', 'India', 3),
    ('Bajirao Mastani', 'Sanjay Leela Bhansali', 'India', 3);

INSERT INTO movies (name, director, origin, categoryid)
VALUES
    ('Baahubali', 'S. S. Rajamouli', 'Kollywood', 4),
    ('Kaithi', 'Lokesh Kanagaraj', 'Kollywood', 4),
    ('Vada Chennai', 'Vetrimaaran', 'Kollywood', 4),
    ('Super Deluxe', 'Thiagarajan Kumararaja', 'Kollywood', 4),
    ('96', 'C. Prem Kumar', 'Kollywood', 4),
    ('Viswasam', 'Siva', 'Kollywood', 4),
    ('Asuran', 'Vetrimaaran', 'Kollywood', 4),
    ('Pariyerum Perumal', 'Mari Selvaraj', 'Kollywood', 4),
    ('KGF: Chapter 1', 'Prashanth Neel', 'Kollywood', 4),
    ('Kaththi', 'A. R. Murugadoss', 'Kollywood', 4),
    ('Sarkar', 'A. R. Murugadoss', 'Kollywood', 4),
    ('Ratsasan', 'Ram Kumar', 'Kollywood', 4),
    ('Vikram Vedha', 'Pushkar-Gayathri', 'Kollywood', 4),
    ('Aruvi', 'Arun Prabhu Purushothaman', 'Kollywood', 4),
    ('Raja Rani', 'Atlee', 'Kollywood', 4),
    ('I', 'S. Shankar', 'Kollywood', 4),
    ('Parasite', 'Bong Joon-ho', 'Kollywood', 4),
    ('Bigil', 'Atlee', 'Kollywood', 4),
    ('Irudhi Suttru', 'Sudha Kongara', 'Kollywood', 4),
    ('Petta', 'Karthik Subbaraj', 'Kollywood', 4),
    ('Aadai', 'Rathna Kumar', 'Kollywood', 4),
    ('Jigarthanda', 'Karthik Subbaraj', 'Kollywood', 4),
    ('Mersal', 'Atlee', 'Kollywood', 4),
    ('Peranbu', 'Ram', 'Kollywood', 4),
    ('Soodhu Kavvum', 'Nalan Kumarasamy', 'Kollywood', 4),
    ('Mayakkam Enna', 'Selvaraghavan', 'Kollywood', 4),
    ('Aruvi', 'Arun Prabhu Purushothaman', 'Kollywood', 4),
    ('Vada Chennai', 'Vetrimaaran', 'Kollywood', 4),
    ('Karnan', 'Mari Selvaraj', 'Kollywood', 4),
    ('Vada Chennai', 'Vetrimaaran', 'Kollywood', 4),
    ('Joker', 'Rajumurugan', 'Kollywood', 4),
    ('Sethupathi', 'S. U. Arun Kumar', 'Kollywood', 4),
    ('Pariyerum Perumal', 'Mari Selvaraj', 'Kollywood', 4),
    ('KGF: Chapter 1', 'Prashanth Neel', 'Kollywood', 4),
    ('Karnan', 'Mari Selvaraj', 'Kollywood', 4),
    ('Kaithi', 'Lokesh Kanagaraj', 'Kollywood', 4),
    ('Soorarai Pottru', 'Sudha Kongara', 'Kollywood', 4),
    ('Jigarthanda', 'Karthik Subbaraj', 'Kollywood', 4),
    ('Asuran', 'Vetrimaaran', 'Kollywood', 4),
    ('Peranbu', 'Ram', 'Kollywood', 4);

    
select * from movies;


